### ISSUE TITLE
Venmo One Touch button iOS SDK

### ISSUE THREAD

**Issue by SolomonBier** [braintree/braintree_ios#103]
Clicking on the Venmo button returns the following error:

BTPaymentButton collection view received didSelectItemAtIndexPath for unknown indexPath. This should never happen.

OneTouch is enabled. **EDIT: PayPal looks like it does not work now. It hooks to the PayPal app and then returns to the original app without updating anything.

**Comment by burnto** [comment]
Thanks @SolomonBier - we'll look into this.

**Comment by burnto** [comment]
@SolomonBier I believe the log statement you are seeing is probably due to a missing `break` statement here:
https://github.com/braintree/braintree_ios/blob/2fd71cfc22232502685b121f112956552f43847a/Braintree/Drop-In/BTPaymentButton.m#L225

We need to add that `break`, obviously.

I would appreciate it if you could confirm my explanation by setting a breakpoint in your own project and stepping through that particular switch and ensuring that you are actually getting into the Venmo case, then falling through to the default case.

But if you're noticing this logging, it sounds like the app switch to Venmo is not actually working for you, which is why you reported this issue. Correct? If so, we should dig into this further.

**Comment by SolomonBier** [comment]
@burnto checking now! I saw that too

**Comment by SolomonBier** [comment]
@burnto any updates on this ?

**Comment by mickeyreiss** [comment]
We've released a fix for the missing `break` in 3.7.1.

**Comment by SolomonBier** [comment]
@mickeyreiss I just updated to 3.8 I believe and this still isn't working, and neither is Paypal.

**Comment by intelliot** [comment]
Is your integration currently using sandbox, or production?

We'll look into this soon. Thanks for your patience.

**Comment by intelliot** [comment]
I'm looking into this now. Are you using CocoaPods, and if so, which version?

Could you provide an example project that exhibits this error? If you don't want to post it on GitHub, you may email it to me: elliot.lee@getbraintree.com

**Comment by intelliot** [comment]
Are you testing this in the Simulator, or on a real device? Which version of iOS?

**Comment by SolomonBier** [comment]
@intelliot real device, and yes I am using pods. I don't think its possible for my to email you my huge repository. I'll reach out to you via email.

**Comment by intelliot** [comment]
Does the problem occur in the Simulator?

I've identified a potential issue with Venmo where the card selector sometimes doesn't appear, but it doesn't seem related to the error you're seeing.

**Comment by intelliot** [comment]
Just worked with @SolomonBier to debug this issue. We successfully solved the two issues:

(1) PayPal: We were not checking the URL correctly, so the AppDelegate wasn't passing the url to Braintree.
(2) Venmo: `CFBundleDisplayName` must be set in Info.plist.

We should clarify our docs to make (1) easier. Also, there's a bug in our SDK that cause "PayPal Error" to display for non-PayPal errors. We'll make sure this error gets surfaced correctly in a future SDK update.

Thank you!

**Comment by intelliot** [comment]
> there's a bug in our SDK that cause "PayPal Error" to display for non-PayPal errors.

Fixed in 7c1465c3ee3cb34f46c441b3d0770fa0cf0f925e
