### ISSUE TITLE
Does not compile in xCode 7

### ISSUE THREAD

**Issue by JesseARWhite** [braintree/braintree_ios#132]
The current main branch is unable to compile in xCode 7.  Lots of errors that need some basic attention, maybe a branch to support this upcoming release?

**Comment by mickeyreiss** [comment]
Absolutely. We'll do that in the next few days and do our best to cut a version when the GM is released.

**Comment by JesseARWhite** [comment]
Thanks!

- Jesse

**Comment by burnto** [comment]
@JesseARWhite take a look at @mickeyreiss's [`xcode-beta` branch](https://github.com/braintree/braintree_ios/tree/xcode-beta) and #133. Feedback appreciated.

**Comment by sobri909** [comment]
Latest Xcode breaks it again. 

> BTMockApplePayPaymentAuthorizationView.m:14:12: Nullability specifier 'nonnull' conflicts with existing specifier 'nullable'

**Comment by amen160** [comment]
@implementation BTAPIResponseParser 
method override for the designated initializer of the superclass '-init' not found

**Comment by orinmurphy** [comment]
@implementation BTAPIResponseParser
Method override for the designated initializer of the superclass '-init' not found

**Comment by athies** [comment]
I am also getting same error as @amen160 and @orinmurphy

**Comment by burnto** [comment]
@amen160 @orinmurphy @athies are you using the `xcode-beta` branch? 

E.g. in your Podfile:

```ruby
pod 'Braintree', :git => 'https://github.com/braintree/braintree_ios.git', :branch => 'xcode-beta'
```

**Comment by orinmurphy** [comment]
@burnto I just updated my Podfile. But now getting 8 errors in BTClient.h
7 Parse issues and 1 Semantic Issue.

Example:
<img width="985" alt="screen shot 2015-08-06 at 16 39 49" src="https://cloud.githubusercontent.com/assets/3251360/9122849/b04b3c64-3c59-11e5-9818-6ea3ef8d1f34.png">

**Comment by skunkworks** [comment]
@orinmurphy Can you confirm that you're using Xcode 7 Beta 4? I see the same error from your screenshot when I use Xcode 6.

**Comment by orinmurphy** [comment]
@skunkworks yes I was using Xcode6

**Comment by burnto** [comment]
@orinmurphy ok thanks. Yep, part of the reason we have these changes in a branch is that it's only compatible with the new Xcode 7 beta.

We'll merge the `xcode-beta` branch into master and up the required Xcode version once there is an Xcode 7 GM.

**Comment by orinmurphy** [comment]
@burnto ah ok, cool. 
Is the xcode-beta branch ok to use in production?

**Comment by burnto** [comment]
@orinmurphy since Xcode 7 is still beta, and since you can't actually submit apps developed in Xcode 7 beta to the app store, I'd say it isn't ready for production yet.

We'll merge this `xcode-beta` branch into master and tag a new release when this work is ready for production. In the meantime, this branch at least unblocks folks like you who are using the Xcode 7 betas.

We haven't seen those Coinbase errors in our integration projects. Can you make sure to clean, delete derived data, and `pod install`?

**Comment by orinmurphy** [comment]
@burnto I've done that, but i'm still seeing those same errors.

**Comment by skunkworks** [comment]
@orinmurphy Please try deleting your `Pods/Braintree` and `Pods/Headers` folder and re-running `pod install`. I have a hunch that Cocoapods has a stale cached copy of our pod.

**Comment by sobri909** [comment]
It would be very desirable to avoid these situations in future. Breaking the tree for both stable and beta makes working on both ... well, it costs extra time and money. 

It didn't need to be this way. 

If we're trying to debug iOS 9 builds at the same time as preparing iOS 8 builds for submission, this is a time wasting mess. 

I'm putting my vote in for not this way next time please.

**Comment by skunkworks** [comment]
@sobri909 @orinmurphy @JesseARWhite Sorry for the inconvenience! I've pushed a new commit to the `xcode-beta` branch that adds Xcode 6 backwards compatibility. We'll reassess the way we add support for Xcode betas in the future.

**Comment by JesseARWhite** [comment]
Since I was referenced on that last comment...

I think you guys have done a great job providing support for iOS9 since beta 1 was released!  This was a fantastic approach - There were a lot of code breaking changes between 6.4 and XCode 7 especially for those of us that are heavy swift adopters.  This is really the only reliable way to address the complex situation of coding for beta versions of iOS and XCode.  I don't believe you have inconvenienced anybody, its just important that people monitor what branches they are pointed at during development.

Thanks again for the quick response!

**Comment by orinmurphy** [comment]
@skunkworks thanks, but i'm still seeing the same 4 errors as above.
Im now running xcode6 with the `xcode-beta`, since you've posted about it being backwards compatible. 

I deleted `Pods/Braintree` and `Pods/Headers` as suggested, and did another `pod install`, but its the same problem...

**Comment by skunkworks** [comment]
@orinmurphy Can you confirm that you can see the following files in your Pods project:

* `BTCoinbaseDefines.h` and `BTCoinbaseDefines.m`
* `BTCoinbaseOAuth.h` and `BTCoinbaseOAuth.m`

<img width="217" alt="screen shot 2015-08-13 at 1 51 30 pm" src="https://cloud.githubusercontent.com/assets/563375/9261417/954c60f0-41c2-11e5-909b-ae4a61ff9d24.png">

Can you also verify that your Podfile does not import the Coinbase SDK directly?

**Comment by orinmurphy** [comment]
@skunkworks yes i can confirm that my podfile does not import Coinbase directly. I also can confirm that the files in my project match what you have in your screenshot.

Take a look at the first `pod install` command in terminal, it removes coinbase?
<img width="727" alt="screen shot 2015-08-13 at 16 59 03" src="https://cloud.githubusercontent.com/assets/3251360/9261558/b00c930a-41dc-11e5-9cd7-b8ce57224637.png">

**Comment by skunkworks** [comment]
@orinmurphy Are there any references to `CoinbaseErrorDomain` in your project? These symbols have been changed.

**Comment by orinmurphy** [comment]
@skunkworks the only results when I search for 'coinbase' in my project are from within the Braintree files

**Comment by skunkworks** [comment]
@orinmurphy You should only see `BTCoinbaseErrorDomain`, never `CoinbaseErrorDomain`. If that's not the case, then there are some files in your project that do not belong there.

**Comment by orinmurphy** [comment]
@skunkworks yes, I only see `BTCoinbaseErrorDomain`.

The only play I see `CoinbaseErrorDomain` is:
`NSString *const BTCoinbaseErrorDomain = @"CoinbaseErrorDomain";`
in `BTCoinbaseDefines.m`

**Comment by skunkworks** [comment]
@orinmurphy Do you want to debug this together on Screenhero? My user name on Screenhero is my github user name at gmail dot com.

**Comment by orinmurphy** [comment]
@skunkworks great, thanks. I just sent you an invite

**Comment by orinmurphy** [comment]
@skunkworks created a new project and moved codebase over. I can confirm that the `xcode-beta` branch is working for me now.

**Comment by skunkworks** [comment]
@orinmurphy I'm glad to hear that did the trick!

**Comment by b051** [comment]
`xcode-beta` doesn't exist anymore, also tried `4.0.0-beta1` branch, breaks, a lot of breaks. on official xcode7.
I hope you guys are working on it, cause I have to pull off braintree to get my projects work.

**Comment by skunkworks** [comment]
@b051 Please try version 3.9.3 or what's currently in `master`. Thanks.
