### ISSUE TITLE
App Crash on Launch After Upgrading Braintree SDK from 5.2 to 6.23.2

### ISSUE THREAD

**Issue by Navdeep2020** [braintree/braintree_ios#1396]
### Braintree SDK Version

6.23.2

### Environment

Both

### Xcode Version

15.4

### OS Version & Device

ios 16

### Integration type

CocoaPods

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

I recently updated the Braintree SDK in my iOS project from version 5.21 to 6.23.2. After making the necessary changes in the Podfile, AppDelegate, and other integration points, the application worked fine during the initial testing.

However, after integrating the SDK into our Customer Portal (CP) and completing all required updates (including pod updates and version upgrades), the app crashes on the launch screen.

Error in console is:
```
 Symbol not found: _$s9Braintree13BTVenmoClientC018openVenmoAppPageInF5StoreyyFTj
  Referenced from: <553D15F4-0932-3EB9-8BA8-34A35971E393> /Users/navsingh/Library/Developer/Xcode/DerivedData/CustomerPortal-hfezrjyacftxxcfidrmywzpmjvgp/Build/Products/Debug-iphonesimulator/Paymentus.framework/Paymentus
  Expected in:     <FFA24E47-75B1-35FA-950D-D83B2BA55116> /Users/navsingh/Library/Developer/CoreSimulator/Devices/54C458E7-E7ED-4D1E-8622-DD15A28DAABA/data/Containers/Bundle/Application/70C6D875-14AF-477C-BE96-BA567043EE66/Customer Portal.app/Frameworks/Braintree.framework/Braintree
```
 

### To reproduce

Steps to Reproduce:

1. Update the Braintree SDK from 5.2 to 6.23.2.
2. Make necessary changes in Podfile, AppDelegate, etc.
3. Integrate the SDK into a any project
4. Perform pod updates and version upgrades.
5. Launch the app.

### Expected behavior

The app should not crash.
Bit confused that line 28 is correct or not.

<img width="998" alt="image" src="https://github.com/user-attachments/assets/c3d613c7-e560-43f6-a7a0-e290a9a7c80a">

**Comment by KunJeongPark** [comment]
Hello, there is a known issue with 6.23.2 which was addressed in 6.23.3
Please upgrade to our latest version. We apologize for the inconvenience.

**Comment by Navdeep2020** [comment]
I have upgraded to 6.23.3 but the error is still same at run time,
Please look at the issue more carefully.

<img width="1071" alt="image" src="https://github.com/user-attachments/assets/6b4b7aa2-e9ce-40a9-a7db-b1fdc847451b">

**Comment by nrajput05** [comment]
Getting the same issue. 
The error states that it can not find BTVenmoClient, see the error below:

`Symbol not found: _$s9Braintree13BTVenmoClientC018openVenmoAppPageInF5StoreyyFTj
  Referenced from: <2B225D39-25E0-3718-A3E1-A2EBE0B88B67> /Users/xyz/Library/Developer/Xcode/DerivedData/CustomerPortal-bjcrubavwaoeufgtdntitbgnmgae/Build/Products/Debug-iphonesimulator/Payin.framework/Payin
  Expected in:     <FE2F0A00-1848-377C-A648-CC9B2871C27D> /Users/xyz/Library/Developer/CoreSimulator/Devices/D8A27BCA-7988-4634-A049-D08D641675AA/data/Containers/Bundle/Application/F64561D8-30E5-46C2-B76C-DBC9D8F31FE7/Customer Portal.app/Frameworks/Braintree.framework/Braintree`
  
I have an xcframework which uses Braintree as a dependency/cocoapods. The app is responsible to provide the pod to my framework. But after migration to 6.23.3 I am getting the above issue.

Also note that when I migrated, all the BTVenmoDriver class names were replaced by BTVenmoClient which is the exact name being printed in the console. 

Please assist at the earliest !

**Comment by himandhawan001** [comment]
+1, found the same issue at my side too and it is blocking my current release 
@KunJeongPark can you create new framework project and add braintree dependencies and add the framework in new application with same dependencies through cocoa pods. You will get the crash.

**Comment by himandhawan001** [comment]
@KunJeongPark can you check the below files. We get the crash as soon as any function is accessed of braintree. Like we use vault method in BTVenmoRequest. If you uncomment the value method, crash will resolve. 

[Github Issue.zip](https://github.com/user-attachments/files/16813335/Github.Issue.zip)

**Comment by himandhawan001** [comment]
Below code contains the error @KunJeongPark 
Steps : 
1. Build TestingBraintreeFramework project and copy the .framework file from Products 
2. Add framework to TestingBraintree Project.
3. Run the code
Now
Uncomment the req.vault = false at line number 36 in TestBraintree file and again repeat same steps. The crash will resolve.

[Github Issue.zip](https://github.com/user-attachments/files/16813457/Github.Issue.zip)

**Comment by KunJeongPark** [comment]
Hello, we've had similar issues reported with 6.23.2 and our crash fix on 6.23.3 has resolved the issue for those merchants.
Please try upgrading to 6.23.3 and let me know if you have further issues.

**Comment by KunJeongPark** [comment]
Thank you for the further information. We will investigate this next week. We are back next Tuesday and we will investigate the issue. Thank you for your patience.

**Comment by Navdeep2020** [comment]
@KunJeongPark To address your questions:

1. All three issues are indeed the same.
2. The problem began after updating the Braintree SDK in our iOS project from version 5.21.0 to 6.23.3.
3. Versions where the issue occurred: 6.23.2, 6.23.3, 6.20.0. 
4. Xcode version used: 15.2.

**Comment by KunJeongPark** [comment]
I was not able to recreate this issue with Xcode 15.3
I will try to test with Xcode 15.4 and Xcode 15.2 as soon as I can.

Steps I took:
1. Create framework with Braintree, Braintree/Venmo and Braintree/DataCollector 
2. Create an Xcode workspace using same dependencies and importing the framework 
3. Try with and without default values set for request objects as mentioned in @himandhawan001 's project

**Comment by Navdeep2020** [comment]
@KunJeongPark I have already tried reinstalling the pods and cleaning the build folder, but the issue persists. I have tested the project on Xcode 15.3, and the problem still occurs on my end. It would be great if you could try running my demo project as well, which is quite small and easy to set up. This way, you can reproduce the issue on your machine.

Additionally, we are seeing the same error when using PayPal (without Venmo), specifically when accessing BTPayPalVaultRequest. The issue occurs if the following line is included:
`req.offerCredit = true`

When we comment this line, the project works fine.

The overall error that we get in the console is 
```
dyld[58658]: Symbol not found: _$s9Braintree24BTPayPalVaultBaseRequestC11offerCreditSbvsTj
  Referenced from: <30AAA43D-16D7-31B2-AB8A-9878BC91C355> /Users/xyz/Library/Developer/CoreSimulator/Devices/51135919-7D72-4FE7-9CF9-3740E1D79569/data/Containers/Bundle/Application/5FE89493-5227-4882-886F-2A299DDF6206/xc15testApp.app/Frameworks/xc15testframework.framework/xc15testframework
  Expected in:     <7C87D6B3-3E20-33A4-BA7A-54AE843AC03F> /Users/xyz/Library/Developer/CoreSimulator/Devices/51135919-7D72-4FE7-9CF9-3740E1D79569/data/Containers/Bundle/Application/5FE89493-5227-4882-886F-2A299DDF6206/xc15testApp.app/Frameworks/Braintree.framework/Braintree
```
[Archive.zip](https://github.com/user-attachments/files/16883726/Archive.zip)

**Comment by KunJeongPark** [comment]
Thank you for providing me with the project. I will look at it.

**Comment by Navdeep2020** [comment]
Hi @KunJeongPark 5.21 was the last working version for us.
We shifted from 5.21 we shifted to 6.23.2,6.23.3(all non-working versions) etc

**Comment by KunJeongPark** [comment]
We were able to successfully compile your app by adding these lines in the Podfile of your app project.
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
```

**Comment by jaxdesmarais** [comment]
Hey all -

Just checking to see if the solution @KunJeongPark provided resolved the issue you all were seeing.

**Comment by Navdeep2020** [comment]
Yes, it worked. Thanks for assisting us, @KunJeongPark

**Comment by jaxdesmarais** [comment]
Hey @Navdeep2020 -

You should be able to set this up in the framework you are building that wraps the Braintree SDK. On the SDK side we are setting this value to true, but since you are building a framework that wraps the Braintree SDK you'd need to set it at that level as well. You may find [this cocoapods GitHub issue](https://github.com/CocoaPods/CocoaPods/issues/11153) helpful as it lists some solutions for building frameworks with dependencies with this flag.
