### ISSUE TITLE
ios Compile error

### ISSUE THREAD

**Issue by x2201783** [braintree/braintree_ios#392]
BraintreePaymentFlow/BraintreePaymentFlow.h file not found,
cocoapods After installation, open ,xcode9.2

**Comment by bluk** [comment]
Can you try running `pod repo update` and `pod update` to ensure that you have the latest code? Thanks.

**Comment by x2201783** [comment]
I tried, it didn't work.

**Comment by RomeHein** [comment]
Same issue here:

```
dyld: Symbol not found: _OBJC_CLASS_$_BTPaymentFlowDriver
  Referenced from: /private/var/containers/Bundle/Application/59081BB3-16FC-4133-85CA-D3B0C9B8FF79/Ladbrokes.app/Frameworks/BraintreeDropIn.framework/BraintreeDropIn
  Expected in: /private/var/containers/Bundle/Application/59081BB3-16FC-4133-85CA-D3B0C9B8FF79/Ladbrokes.app/Frameworks/Braintree.framework/Braintree
 in /private/var/containers/Bundle/Application/59081BB3-16FC-4133-85CA-D3B0C9B8FF79/Ladbrokes.app/Frameworks/BraintreeDropIn.framework/BraintreeDropIn
```

latest pod version, Xcode 9.2

**Comment by skunkworks** [comment]
We're working on a fix for this, thanks for reporting it.

**Comment by skunkworks** [comment]
Hi, please update to [4.12.0](https://github.com/braintree/braintree_ios/releases/tag/4.12.0) -- it should resolve this issue. Thanks for your patience.

**Comment by RomeHein** [comment]
Hmm, still not working for me. I've tried deleting my pods, clearing the cache and reinstalling, I still get that error. 
It's happening only when I add the pod "BraintreeDropIn", with any version of that pod (6.1.0, 6.0.0 etc)

**Comment by demerino** [comment]
@RomeHein Can you help us understand more about your particular integration? Is this an issue with the Braintree Demo app or your own app? Any extra info will help us narrow down the cause.

- Which version of CocoaPods are you using? 
- Which version of Drop-in are you trying to use?
- Which version of `Braintree/Core` does your `Podfile.lock` include?
- What order are you executing the cache clearing and the Xcode project cleans? 
- Is it a Swift or Objc app?

**Comment by skunkworks** [comment]
@RomeHein I also want to make sure there isn't a mismatch between the versions of `Braintree` and `BraintreeDropIn`. You can check the version of `BraintreeCore` by checking the Podfile.lock file, or by navigating inside your Xcode workspace to `Pods > Braintree > Core > Braintree-Version.h`.

It should be >= 4.11.0.

**Comment by x2201783** [comment]
Yes, thank you.

**Comment by Sub-Zero-1** [comment]
Same here. BraintreePaymentFlow/BraintreePaymentFlow.h file not found in my Bridiging file.

Podfile:
frameworks
  use_frameworks!
  # Pods for iPostcard
  pod 'PMAlertController'
  pod 'Braintree'
  pod 'Braintree/PaymentFlow'
  pod 'BraintreeDropIn'
  pod 'Braintree/PayPal'
  pod 'Firebase'
....
end



After removed and added all Braintree dependencies again (I do not see PaymentFlow is getting installed at all!):
Analyzing dependencies
Downloading dependencies
Using AZSClient (0.2.6)
Installing Braintree 4.27.1
Installing BraintreeDropIn (7.4.0)
Using ColorSlider (4.3)
....
Generating Pods project
Integrating client project
Sending stats


What can I do?

**Comment by sestevens** [comment]
@Sub-Zero-1 Do you see `Braintree/PaymentFlow` in the `PODS` section of Podfile.lock after running `pod install`?

**Comment by Sub-Zero-1** [comment]
@sestevens 

Yes, I think so:  

  - Braintree (4.27.1):
    - Braintree/Card (= 4.27.1)
    - Braintree/Core (= 4.27.1)
    - Braintree/PayPal (= 4.27.1)
    - Braintree/UI (= 4.27.1)
  - Braintree/Card (4.27.1):
    - Braintree/Core
  - Braintree/Core (4.27.1)
  - Braintree/PaymentFlow (4.27.1):
    - Braintree/Card
    - Braintree/Core
    - Braintree/PayPalOneTouch
  - Braintree/PayPal (4.27.1):
    - Braintree/Core
    - Braintree/PayPalOneTouch
  - Braintree/PayPalDataCollector (4.27.1):
    - Braintree/Core
    - Braintree/PayPalUtils
  - Braintree/PayPalOneTouch (4.27.1):
    - Braintree/Core
    - Braintree/PayPalDataCollector
    - Braintree/PayPalUtils
  - Braintree/PayPalUtils (4.27.1)
  - Braintree/UI (4.27.1):
    - Braintree/Card
    - Braintree/Core
  - Braintree/UnionPay (4.27.1):
    - Braintree/Card
    - Braintree/Core
  - BraintreeDropIn (7.4.0):
    - BraintreeDropIn/DropIn (= 7.4.0)
  - BraintreeDropIn/DropIn (7.4.0):
    - Braintree/Card (~> 4.27)
    - Braintree/Core (~> 4.27)
    - Braintree/PaymentFlow (~> 4.27)
    - Braintree/PayPal (~> 4.27)
    - Braintree/UnionPay (~> 4.27)
    - BraintreeDropIn/UIKit
  - BraintreeDropIn/UIKit (7.4.0)

**Comment by Sub-Zero-1** [comment]
@sestevens Solved it.

#import "Braintree/BraintreePaymentFlow.h"

instead of:

#import "BraintreePaymentFlow.h"

did the trick!
