### ISSUE TITLE
Not able to make a build for Demo project

### ISSUE THREAD

**Issue by sourav9693** [braintree/braintree_ios#437]
* SDK/Library version: 4.21
* Environment:  Sandbox
* iOS Version and Device: Xcode 10 and ios 10
* Integration type and version: CocoaPods 1.0.5

getting bellow mention issue. Not able to make a build. please help me.
'BraintreePayPal/BraintreePayPal.h' file not found

**Comment by demerino** [comment]
Did you run `pod install` first? We've occasionally seen this issue and `cleaning` the project and also purging your `derived data` directory should resolve the issue.

**Comment by kkorouei** [comment]
I have the same issue. Cleaning and deleting derived data still doesn't resolve the issue.

**Comment by billwerges** [comment]
Hi @sourav9693 and @kkorouei,

This issue should be fixed in the latest release. You will have to run `pod install` again after updating for the fix to work however.
