### ISSUE TITLE
Targeting iOS 15 will not compile because of deprecated UIApplication.windows

### ISSUE THREAD

**Issue by gomera** [braintree/braintree_ios#884]
**Integration Details (please complete the following information):**
 - Braintree SDK Version: 5.14.0
 - Environment: Any
 - iOS Version: iOS 15.0 and up
 - Xcode Version: [e.g. Xcode 13.4]
 - Device: iPhone 13 Pro Max
 - Integration type & version: CocoaPods 1.11.3
 - Development Processor Type: Intel

**Describe the bug**
We are currently targeting iOS 13 but according to our data, iOS 13 is less than 0.2% of our users and iOS 14 ~ 4%, so we decided to start targeting iOS 15 so that we cat start enjoying all the benefits of Swift 5.5. However, after changing the target to 15.0, the app does not compile anymore because `BTPayPalDriver` Braintree is using `UIApplication.windows` inside `presentationAnchorForWebAuthenticationSession` which was completely deprecated since iOS 15. A probably solution could be something similar to this:
```
#if __IPHONE_OS_VERSION_MIN_REQUIRED >= __IPHONE_15_0
    return ((UIWindowScene *)UIApplication.sharedApplication.connectedScenes.allObjects.firstObject).windows.firstObject;
#else
    return UIApplication.sharedApplication.windows.firstObject;
#endif
```

**To Reproduce**
1. Go to your project and select 15.0 as Deployment Target 
2. Go to your target and then check on Deployment info that you also have 15.0 
3. Compile

**Expected behavior**
Compile does not show any error and paypal integration works as before.

**Screenshots**
![Screen Shot 2022-10-21 at 18 55 29](https://user-images.githubusercontent.com/1063134/197294613-f6ba033f-5408-4689-8183-5e919e792cce.png)

**Comment by scannillo** [comment]
Hi @gomera - thanks for bringing this to our attention. We will work on a fix! But in the meantime, you can set `Treat Warnings as Errors` in your Build Settings to `NO` to unblock yourself.

**Comment by gomera** [comment]
hi @scannillo that flag is already set in `NO` and actually that workaround will not work since this is not a warning, but an actual error. It was a warning before, cause that property was going to be deprecated but on iOS 15 it was completely removed.

**Comment by scannillo** [comment]
According to [Apple's docs](https://developer.apple.com/documentation/uikit/uiapplication/1623104-windows), the `UIApplication.windows` property is deprecated and not removed. I am also to see just a warning, instead of an error, using Xcode 13.4, like you specified.

![Screen Shot 2022-10-24 at 10 58 51 AM](https://user-images.githubusercontent.com/35243507/197572067-e6de11c3-3259-479d-965e-78f18a46fb02.png)

Toggling `Treat Warnings as Errors` does indeed work for me in a sample project. But depending on your project setup, just need to make sure you're adjusting it in the right places in your Xcode proj.

Like I said - we will work on getting a fix out shortly and will update you!

**Comment by gomera** [comment]
mmm, not sure why it shows that as a warning to you. 

I double check that property on Braintree: 
<img width="769" alt="Screen Shot 2022-10-24 at 13 09 32" src="https://user-images.githubusercontent.com/1063134/197574075-075c2324-9bb0-4522-a4f9-869d3f7558f2.png">

And then on Pod:
<img width="701" alt="Screen Shot 2022-10-24 at 13 09 40" src="https://user-images.githubusercontent.com/1063134/197574203-548564d9-cc9e-4b3e-b2ca-e43c665b7241.png">

and as a matter of fact, it is also set to `No` on my project.

So far the only workaround it works for me is setting the target to 14.7 on the Podfile.

**Comment by jaxdesmarais** [comment]
Hello @gomera -

This fix has been released in [version 5.15.0 of the SDK](https://github.com/braintree/braintree_ios/releases/tag/5.15.0). Please let us know if you continue to run into issues after making this update.

**Comment by gomera** [comment]
Hi @jaxdesmarais I will take a look at this later today, thanks for the quick fix !

**Comment by gomera** [comment]
Hi @jaxdesmarais the issue is still present, cause the fix was an if / else statement instead of macros, so that part of the code will still try to compile. However, I believe what @scannillo said is still valid, this should be a warning and not an error, but for some unknown reason it is not happening. Probably there is something on the setup of your framework. For example, in my project, I have another dependency that has exactly the same issue, but over there, it is shown correctly as a warning. Both projects have objc code, but Braintree have some specific Swift things that the other doesn't. I happy to help in anything you need.

![Screen Shot 2022-10-27 at 10 47 02](https://user-images.githubusercontent.com/1063134/198306268-eb5384f7-fea9-4753-9c78-fb52700d68a9.png)

There is workaround for this which involves turning off warnings just for Braintree pod, but this may hide other potential issues in the future.

```
pod 'Braintree', :inhibit_warnings => true
```
